### PR TITLE
New version

### PR DESCRIPTION
**Pull request by ravescovi**
Cleanup, new robos, etc.

### CODE REVIEW

**Comment by decarlof** [comment]
will not automatically merge; it looks you forgot to resync before starting the changes; I will tray to merge manually, if takes to much time we can just start fresh with your version.

**Comment by ravescovi** [comment]
I think it is because i deleted too many files.

Rafael Vescovi

**Comment by decarlof** [comment]
no deleting files is fine if you resync and I don't touch again till you are done (see https://github.com/decarlof/automo/network).

**Comment by ravescovi** [comment]
should i resync.. change the files and do another PR?

Rafael Vescovi

**Comment by decarlof** [comment]
done!

**Comment by ravescovi** [comment]
saw it.. looks good..

What are the next steps? Do you want to do a real test before the beamtime

## (i can arrange my time)?

Rafael Vescovi

**Pull request merged**
